// Enhanced Theme System - Dark Charcoal + Neon Accents
// Supports light mode, dark mode, and the new "neon" dark mode

export const lightTheme = {
  mode: 'light',
  colors: {
    background: '#FAF9F8',
    surface: '#FFFFFF',
    surfaceSecondary: '#F3F4F6',
    surfaceGlass: 'rgba(255, 255, 255, 0.7)',
    text: '#1A1A1A',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    primary: '#7C3AED',
    primaryLight: '#EDE9FE',
    primaryGlow: 'rgba(124, 58, 237, 0.3)',
    secondary: '#10B981',
    secondaryLight: '#D1FAE5',
    secondaryGlow: 'rgba(16, 185, 129, 0.3)',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    sidebar: '#FFFFFF',
    sidebarText: '#374151',
    sidebarActive: '#7C3AED',
    sidebarActiveBg: '#EDE9FE',
    chartPurple: '#7C3AED',
    chartGreen: '#10B981',
    chartOrange: '#F59E0B',
    chartBlue: '#3B82F6',
    statusActive: '#10B981',
    statusFocus: '#7C3AED',
    statusOffline: '#6B7280',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    s: 4,
    m: 8,
    l: 12,
    xl: 16,
    xxl: 24,
    round: 999,
  },
  typography: {
    header: { fontSize: 28, fontWeight: '700', color: '#1A1A1A' },
    subHeader: { fontSize: 18, fontWeight: '600', color: '#1A1A1A' },
    body: { fontSize: 14, color: '#1A1A1A' },
    bodySmall: { fontSize: 12, color: '#6B7280' },
    caption: { fontSize: 11, color: '#9CA3AF' },
    button: { fontSize: 14, fontWeight: '600', color: '#FFFFFF' },
    stat: { fontSize: 24, fontWeight: '700', color: '#1A1A1A' },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    glow: {
      shadowColor: '#7C3AED',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 16,
      elevation: 8,
    },
  },
  glass: {
    background: 'rgba(255, 255, 255, 0.7)',
    blur: 12,
    border: 'rgba(255, 255, 255, 0.2)',
  },
};

export const darkTheme = {
  mode: 'dark',
  colors: {
    background: '#0D0D0F',
    surface: '#1A1A1F',
    surfaceSecondary: '#252529',
    surfaceGlass: 'rgba(26, 26, 31, 0.7)',
    text: '#FFFFFF',
    textSecondary: '#A1A1AA',
    textMuted: '#52525B',
    primary: '#A855F7',
    primaryLight: '#2D1B4E',
    primaryGlow: 'rgba(168, 85, 247, 0.4)',
    secondary: '#10B981',
    secondaryLight: '#064E3B',
    secondaryGlow: 'rgba(16, 185, 129, 0.4)',
    success: '#22C55E',
    warning: '#FBBF24',
    error: '#EF4444',
    border: '#2D2D35',
    borderLight: '#1F1F25',
    sidebar: '#0D0D0F',
    sidebarText: '#A1A1AA',
    sidebarActive: '#A855F7',
    sidebarActiveBg: '#2D1B4E',
    chartPurple: '#A855F7',
    chartGreen: '#22C55E',
    chartOrange: '#FBBF24',
    chartBlue: '#60A5FA',
    statusActive: '#22C55E',
    statusFocus: '#A855F7',
    statusOffline: '#52525B',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    s: 4,
    m: 8,
    l: 12,
    xl: 16,
    xxl: 24,
    round: 999,
  },
  typography: {
    header: { fontSize: 28, fontWeight: '700', color: '#FFFFFF' },
    subHeader: { fontSize: 18, fontWeight: '600', color: '#FFFFFF' },
    body: { fontSize: 14, color: '#FFFFFF' },
    bodySmall: { fontSize: 12, color: '#A1A1AA' },
    caption: { fontSize: 11, color: '#52525B' },
    button: { fontSize: 14, fontWeight: '600', color: '#FFFFFF' },
    stat: { fontSize: 24, fontWeight: '700', color: '#FFFFFF' },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 4,
    },
    glow: {
      shadowColor: '#A855F7',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 10,
    },
    glowGreen: {
      shadowColor: '#22C55E',
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 10,
    },
  },
  glass: {
    background: 'rgba(26, 26, 31, 0.7)',
    blur: 12,
    border: 'rgba(255, 255, 255, 0.08)',
  },
};

// Export default theme for backward compatibility
export const theme = darkTheme;
