// Theme definitions for dark and light modes

export const lightTheme = {
  mode: 'light',
  colors: {
    background: '#FAF9F8',
    surface: '#FFFFFF',
    surfaceSecondary: '#F3F4F6',
    text: '#1A1A1A',
    textSecondary: '#6B7280',
    textMuted: '#9CA3AF',
    primary: '#7C3AED',
    primaryLight: '#EDE9FE',
    success: '#10B981',
    successLight: '#D1FAE5',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    error: '#EF4444',
    errorLight: '#FEE2E2',
    border: '#E5E7EB',
    borderLight: '#F3F4F6',
    sidebar: '#FFFFFF',
    sidebarText: '#374151',
    sidebarActive: '#7C3AED',
    sidebarActiveBg: '#EDE9FE',
    chartPurple: '#7C3AED',
    chartGreen: '#10B981',
    chartOrange: '#F59E0B',
    chartBlue: '#3B82F6',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    s: 4,
    m: 8,
    l: 12,
    xl: 16,
    round: 999,
  },
  typography: {
    header: { fontSize: 28, fontWeight: '700', color: '#1A1A1A' },
    subHeader: { fontSize: 18, fontWeight: '600', color: '#1A1A1A' },
    body: { fontSize: 14, color: '#1A1A1A' },
    bodySmall: { fontSize: 12, color: '#6B7280' },
    caption: { fontSize: 11, color: '#9CA3AF' },
    button: { fontSize: 14, fontWeight: '600', color: '#FFFFFF' },
    stat: { fontSize: 24, fontWeight: '700', color: '#1A1A1A' },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
  },
};

export const darkTheme = {
  mode: 'dark',
  colors: {
    background: '#0F0F0F',
    surface: '#1A1A1A',
    surfaceSecondary: '#252525',
    text: '#FFFFFF',
    textSecondary: '#A1A1A1',
    textMuted: '#6B6B6B',
    primary: '#A855F7',
    primaryLight: '#2D1F47',
    success: '#22C55E',
    successLight: '#14532D',
    warning: '#FBBF24',
    warningLight: '#451A03',
    error: '#EF4444',
    errorLight: '#450A0A',
    border: '#2D2D2D',
    borderLight: '#1F1F1F',
    sidebar: '#1A1A1A',
    sidebarText: '#A1A1A1',
    sidebarActive: '#A855F7',
    sidebarActiveBg: '#2D1F47',
    chartPurple: '#A855F7',
    chartGreen: '#22C55E',
    chartOrange: '#FBBF24',
    chartBlue: '#60A5FA',
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    s: 4,
    m: 8,
    l: 12,
    xl: 16,
    round: 999,
  },
  typography: {
    header: { fontSize: 28, fontWeight: '700', color: '#FFFFFF' },
    subHeader: { fontSize: 18, fontWeight: '600', color: '#FFFFFF' },
    body: { fontSize: 14, color: '#FFFFFF' },
    bodySmall: { fontSize: 12, color: '#A1A1A1' },
    caption: { fontSize: 11, color: '#6B6B6B' },
    button: { fontSize: 14, fontWeight: '600', color: '#FFFFFF' },
    stat: { fontSize: 24, fontWeight: '700', color: '#FFFFFF' },
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
      elevation: 1,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.4,
      shadowRadius: 8,
      elevation: 3,
    },
  },
};

// Export default theme for backward compatibility
export const theme = lightTheme;
